name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 1) Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2) Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3) Setup Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    # 4) Build APK release
    - name: Build APK
      run: ./gradlew assembleRelease

    # 5) Upload APK sebagai *artifact*
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: TachiyomiSYâ€‘APK
        path: app/build/outputs/apk/release/app-release.apk
